// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSudoInitialized():Promise<boolean>;

export function EnsureZeroTierInstalled():Promise<void>;

export function GetAutoMountConfig():Promise<string>;

export function GetCredentials(arg1:string):Promise<string>;

export function GetHomeDir():Promise<string>;

export function GetRuntimeMountDir():Promise<string>;

export function GetSystemUptime():Promise<string>;

export function GetZeroTierInfo():Promise<string>;

export function InitSudoPassword(arg1:string):Promise<void>;

export function JoinZeroTierNetwork(arg1:string):Promise<string>;

export function LeaveZeroTierNetwork(arg1:string):Promise<string>;

export function ListMounts():Promise<string>;

export function ListSMBShares(arg1:string,arg2:string,arg3:string):Promise<string>;

export function ListZeroTierNetworks():Promise<string>;

export function MountSMB(arg1:string,arg2:string,arg3:string,arg4:string,arg5:string,arg6:string):Promise<void>;

export function OpenQuickAccess():Promise<void>;

export function ProcessAutoMount():Promise<void>;

export function SaveAutoMountConfig(arg1:string):Promise<void>;

export function SaveCredentials(arg1:string,arg2:string):Promise<void>;

export function ScanLocalDevices():Promise<string>;

export function SelectMountDirectory():Promise<string>;

export function TestDeviceConnection(arg1:string):Promise<string>;

export function UnmountAll():Promise<void>;

export function UnmountSMB(arg1:string,arg2:boolean):Promise<void>;
