// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function CheckSudoInitialized() {
  return window['go']['main']['App']['CheckSudoInitialized']();
}

export function EnsureZeroTierInstalled() {
  return window['go']['main']['App']['EnsureZeroTierInstalled']();
}

export function GetAutoMountConfig() {
  return window['go']['main']['App']['GetAutoMountConfig']();
}

export function GetCredentials(arg1) {
  return window['go']['main']['App']['GetCredentials'](arg1);
}

export function GetHomeDir() {
  return window['go']['main']['App']['GetHomeDir']();
}

export function GetRuntimeMountDir() {
  return window['go']['main']['App']['GetRuntimeMountDir']();
}

export function GetSystemUptime() {
  return window['go']['main']['App']['GetSystemUptime']();
}

export function GetZeroTierInfo() {
  return window['go']['main']['App']['GetZeroTierInfo']();
}

export function InitSudoPassword(arg1) {
  return window['go']['main']['App']['InitSudoPassword'](arg1);
}

export function JoinZeroTierNetwork(arg1) {
  return window['go']['main']['App']['JoinZeroTierNetwork'](arg1);
}

export function LeaveZeroTierNetwork(arg1) {
  return window['go']['main']['App']['LeaveZeroTierNetwork'](arg1);
}

export function ListMounts() {
  return window['go']['main']['App']['ListMounts']();
}

export function ListSMBShares(arg1, arg2, arg3) {
  return window['go']['main']['App']['ListSMBShares'](arg1, arg2, arg3);
}

export function ListZeroTierNetworks() {
  return window['go']['main']['App']['ListZeroTierNetworks']();
}

export function MountSMB(arg1, arg2, arg3, arg4, arg5, arg6) {
  return window['go']['main']['App']['MountSMB'](arg1, arg2, arg3, arg4, arg5, arg6);
}

export function OpenQuickAccess() {
  return window['go']['main']['App']['OpenQuickAccess']();
}

export function ProcessAutoMount() {
  return window['go']['main']['App']['ProcessAutoMount']();
}

export function SaveAutoMountConfig(arg1) {
  return window['go']['main']['App']['SaveAutoMountConfig'](arg1);
}

export function SaveCredentials(arg1, arg2) {
  return window['go']['main']['App']['SaveCredentials'](arg1, arg2);
}

export function ScanLocalDevices() {
  return window['go']['main']['App']['ScanLocalDevices']();
}

export function SelectMountDirectory() {
  return window['go']['main']['App']['SelectMountDirectory']();
}

export function TestDeviceConnection(arg1) {
  return window['go']['main']['App']['TestDeviceConnection'](arg1);
}

export function UnmountAll() {
  return window['go']['main']['App']['UnmountAll']();
}

export function UnmountSMB(arg1, arg2) {
  return window['go']['main']['App']['UnmountSMB'](arg1, arg2);
}
